### ISSUE TITLE
Alternative app

### ISSUE THREAD

**Issue by nickyrong** [bcgov/HYDAT_Data_Viewer_App#14]
There's currently an alternative to this application that does the same thing (pulling & summarizing HYDAT data, plus ability to do simple flood frequency analysis)
https://github.com/nickyrong/ShinyCFA

**Comment by boshek** [comment]
Very cool! If you wanted to submit a PR to the [tidyhydat](https://github.com/ropensci/tidyhydat) repo we could highlight the app over there.
